import type {
  AdaptedMaterialOutput,
  ExplanationOutput,
} from "./schemas";
import type { AIProvider, ExplainSelectedTextInput, GenerateAdaptedMaterialInput } from "./types";

/**
 * MockAIProvider：仅用于测试（vitest / seed 演示），不应用于正常使用。
 * 通过环境变量 MOCK_AI=1 时由工厂返回；正式运行不应设置该变量。
 */
export class MockAIProvider implements AIProvider {
  readonly name = "mock";

  async generateAdaptedMaterial(input: GenerateAdaptedMaterialInput): Promise<AdaptedMaterialOutput> {
    const base = input.originalText.trim();
    const title = `A Short Reading (${input.targetLevel})`;
    const adaptedText = `This is a short English article written for ${input.targetLevel} learners. It keeps the main ideas of the original material. ${base ? `The original text is: ${base.slice(0, 120)}` : ""} We hope you enjoy reading it and learn some useful words.`;
    return {
      title,
      adaptedText,
      detectedSourceLanguage: "zh",
      learningItems: [
        {
          text: "enjoy",
          itemType: "word",
          meaningZh: "享受；喜欢",
          explanationEn: "to get pleasure from something",
          writingUsage: "Example: I enjoy reading English novels. Use it when expressing likes in your essay.",
          sourceSentence: "We hope you enjoy reading it and learn some useful words.",
        },
        {
          text: "useful words",
          itemType: "phrase",
          meaningZh: "有用的词汇",
          explanationEn: "words that are helpful to know",
          writingUsage: "Example: Learning useful words is important. Use it when talking about language learning.",
          sourceSentence: "We hope you enjoy reading it and learn some useful words.",
        },
      ],
    };
  }

  async explainSelectedText(input: ExplainSelectedTextInput): Promise<ExplanationOutput> {
    return {
      meaningZh: `“${input.text}”的中文释义（Mock 生成）`,
      explanationEn: `A simple English explanation of "${input.text}" (generated by MockAIProvider).`,
      writingUsage: `Example: Use "${input.text}" in a sentence. (generated by MockAIProvider)`,
    };
  }
}