import type {
  AdaptedMaterialOutput,
  ExplanationOutput,
  PracticeSentenceItem,
  TranslationJudgement,
} from "./schemas";
import type {
  AIProvider,
  ExplainSelectedTextInput,
  GenerateAdaptedMaterialInput,
  GeneratePracticeSentencesInput,
  JudgeTranslationInput,
  RefineUserSentencesInput,
} from "./types";

/**
 * MockAIProvider：仅用于测试（vitest / seed 演示），不应用于正常使用。
 * 通过环境变量 MOCK_AI=1 时由工厂返回；正式运行不应设置该变量。
 */
export class MockAIProvider implements AIProvider {
  readonly name = "mock";

  async generateAdaptedMaterial(input: GenerateAdaptedMaterialInput): Promise<AdaptedMaterialOutput> {
    const base = input.originalText.trim();
    const title = `A Short Reading (${input.targetLevel})`;
    const adaptedText = `This is a short English article written for ${input.targetLevel} learners. It keeps the main ideas of the original material. ${base ? `The original text is: ${base.slice(0, 120)}` : ""} We hope you enjoy reading it and learn some useful words.`;
    return {
      title,
      adaptedText,
      detectedSourceLanguage: "zh",
      learningItems: [
        {
          text: "enjoy",
          itemType: "word",
          meaningZh: "享受；喜欢",
          explanationEn: "to get pleasure from something",
          writingUsage: "Example: I enjoy reading English novels. Use it when expressing likes in your essay.",
          sourceSentence: "We hope you enjoy reading it and learn some useful words.",
        },
        {
          text: "useful words",
          itemType: "phrase",
          meaningZh: "有用的词汇",
          explanationEn: "words that are helpful to know",
          writingUsage: "Example: Learning useful words is important. Use it when talking about language learning.",
          sourceSentence: "We hope you enjoy reading it and learn some useful words.",
        },
      ],
    };
  }

  async explainSelectedText(input: ExplainSelectedTextInput): Promise<ExplanationOutput> {
    return {
      meaningZh: `“${input.text}”的中文释义（Mock 生成）`,
      explanationEn: `A simple English explanation of "${input.text}" (generated by MockAIProvider).`,
      writingUsage: `Example: Use "${input.text}" in a sentence. (generated by MockAIProvider)`,
    };
  }

  async judgeTranslation(input: JudgeTranslationInput): Promise<TranslationJudgement> {
    const user = input.userTranslation.trim().toLowerCase();
    const ref = input.referenceTranslation.trim().toLowerCase();
    const roughMatch =
      user.length > 0 &&
      (user === ref || (user.length > 20 && ref.length > 20 && user.split(" ").length >= ref.split(" ").length - 2));
    const passed = roughMatch || (user.length > 0 && !user.includes("??"));
    return {
      score: passed ? 4 : 2,
      passed,
      feedback: passed
        ? "意思表达完整，可以继续下一题。"
        : "部分信息点没有表达清楚，建议对照参考译文再改一版。",
      suggestions: passed ? [] : [input.referenceTranslation],
    };
  }

  async generatePracticeSentences(
    input: GeneratePracticeSentencesInput,
  ): Promise<PracticeSentenceItem[]> {
    const lifeBank: Array<[string, string]> = [
      ["今天天气真不错，我们出去走走吧。", "The weather is really nice today. Let's go out for a walk."],
      ["请问这附近有地铁站吗？", "Excuse me, is there a subway station nearby?"],
      ["我想订一个靠窗的位置。", "I'd like to book a table by the window."],
      ["这双鞋有点小，有大一码的吗？", "These shoes are a bit small. Do you have a larger size?"],
      ["我们好久没见了，最近怎么样？", "Long time no see. How have you been?"],
      ["麻烦把空调调低一点。", "Could you turn the air conditioning down a bit?"],
      ["请问去机场要多久？", "How long does it take to get to the airport?"],
      ["这道菜有点咸，不过挺好吃的。", "This dish is a bit salty, but it's pretty good."],
      ["帮我拍张照片好吗？", "Could you take a photo for me?"],
      ["我感冒了，嗓子有点疼。", "I've caught a cold and my throat hurts a bit."],
    ];
    const workBank: Array<[string, string]> = [
      ["这个需求下周能完成吗？", "Can this requirement be finished by next week?"],
      ["请把会议纪要发给大家。", "Please send the meeting minutes to everyone."],
      ["我下午有个会，三点前不方便接电话。", "I have a meeting this afternoon, so I won't be available for calls until three."],
      ["这个方案我们需要再讨论一下。", "We need to discuss this proposal a bit more."],
      ["您方便约个时间详聊吗？", "Would you be available for a longer chat sometime?"],
      ["这个 bug 我已经定位到了，正在修复。", "I've located the bug and I'm working on the fix."],
      ["麻烦您尽快回复我。", "Could you get back to me as soon as possible?"],
      ["这周进展不大，主要是被数据问题卡住了。", "We didn't make much progress this week, mainly because we got stuck on a data issue."],
      ["我会在今天下班前更新进度。", "I'll update you on the progress before the end of today."],
      ["这个价格我们能再谈谈吗？", "Is there any room to negotiate on the price?"],
    ];

    const existing = new Set(input.existingTexts.map((t) => t.trim()));
    const lifePool = lifeBank.filter(([zh]) => !existing.has(zh));
    const workPool = workBank.filter(([zh]) => !existing.has(zh));
    const lifeSrc = lifePool.length > 0 ? lifePool : lifeBank;
    const workSrc = workPool.length > 0 ? workPool : workBank;

    const count = Math.min(Math.max(input.count, 1), 10);
    const result: PracticeSentenceItem[] = [];
    for (let i = 0; i < count; i++) {
      const [zhText, enReference] = (i % 2 === 0 ? lifeSrc : workSrc)[Math.floor(i / 2) % Math.max(lifeSrc.length, workSrc.length)];
      result.push({ zhText, enReference, scene: i % 2 === 0 ? "life" : "work" });
    }
    return result;
  }

  async refineUserSentences(input: RefineUserSentencesInput): Promise<PracticeSentenceItem[]> {
    const existing = new Set(input.existingTexts.map((t) => t.trim()));
    const parts = input.text
      .split(/[。！？!?；;]/)
      .map((s) => s.trim())
      .filter((s) => s.length >= 5 && !existing.has(s));
    if (parts.length === 0) {
      parts.push(input.text.trim());
    }
    return parts.slice(0, 10).map((zhText) => ({
      zhText,
      enReference: `I believe ${zhText} matters a lot in daily life. (Mock translation)`,
      scene: zhText.includes("工作") || zhText.includes("会议") || zhText.includes("客户") ? "work" : "life",
    }));
  }
}
